### PR TITLE
Added the list of content roots of all modules in the project

### PR DESCRIPTION
**Pull request by vermapratyush**
Added the list of content roots of all modules in the project for auto completion in PerlPackageCompletionProvider

### CODE REVIEW

**Comment by vermapratyush** [comment]
When using the "use" keyword in Perl. The auto suggest shows suggestions from dependent modules, and omits suggestions of modules within the project scope.
This change add the content root of the project to the scan list. So that modules within the project comes up in the auto suggest.

**Comment by hurricup** [comment]
All package files being resolved relatively to class roots. Class roots may be marked as 'Libraries' in the project structure or added by SDK from default `@INC`. What this change gives us? Example please.

**Comment by vermapratyush** [comment]
My bad.
The project I was working on did not have class roots set as "Libraries", hence was not coming up in suggestion. After setting the same, it is working fine.

**Comment by hurricup** [comment]
No problem. Howewer, https://github.com/hurricup/Perl5-IDEA/wiki/Getting-started might be really useful :)

**Pull request closed without merging**
